### ISSUE TITLE
Custom Containers Deployment

### ISSUE THREAD

**Issue by cml-paul** [Onemind-Services-LLC/cloudmydc-docs#103] opened 2024-03-15 06:28 UTC
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/container/container-deployment/custom-containers-deployment

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163177555/c13b4cbb-34e9-48ed-a53e-e95c18082ec4)

**Comment by VKumar786** [comment] 2024-03-18 05:02
Duplicate of PR #91

**Closed by VKumar786** 2024-03-18 05:02 UTC
Labels: type: docs
