### ISSUE TITLE
Environment Import

### ISSUE THREAD

**Issue by cml-paul** [Onemind-Services-LLC/cloudmydc-docs#94] opened 2024-03-13 19:29 UTC
### Change Type

Correction

### Proposed Changes

https://docs.cloudmydc.com/environment-management/environment-export-and-import/environment-import

![image](https://github.com/Onemind-Services-LLC/cloudmydc-docs/assets/163177555/fa1ec426-9635-4284-a008-ccab672ce050)

**Comment by VKumar786** [comment] 2024-03-18 04:45
Duplicate of #93

**Closed by VKumar786** 2024-03-18 04:45 UTC
Labels: type: docs
